name: Test Self-hosted Runner

on:
  push:
    branches: [ main ]
    paths:
      - 'app.py'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  runner-test:
    runs-on: [self-hosted, macOS, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Run Flask App (dry test)
        run: |
          echo "✅ Runner is working correctly."

