name: Test Runner

on:
  push:
    branches: [ main ]
    paths:
      - 'app.py'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, macOS, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Python version
        run: python3 --version

      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt

