<<<<<<< HEAD
name: CI Pipeline
=======
name: Simple CI

>>>>>>> dc1631c
on:
  push:
    branches: [ main ]
    paths:
      - 'app.py'
      - 'requirements.txt'
      - 'Makefile'
  workflow_dispatch:
jobs:
<<<<<<< HEAD
  build-api:
=======
  build:
>>>>>>> dc1631c
    runs-on: [self-hosted, macOS, X64]
    steps:
<<<<<<< HEAD
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: make build
=======
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --no-cache-dir -r requirements.txt

>>>>>>> dc1631c
