name: CI Pipeline

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: [self-hosted, flask-ci-runner]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

