name: CI Pipeline

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: [self-hosted, macOS, X64]

    steps:
      - uses: actions/checkout@v4

      - name: Build (install dependencies)
        run: make build

