name: CI Pipeline
on:
  push:
    branches: [ main ]
    paths:
      - 'app.py'
      - 'requirements.txt'
      - 'Makefile'
  workflow_dispatch:
jobs:
  build-api:
    runs-on: [self-hosted, macOS, X64]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: make build
